# Generated by Django 5.1.2 on 2024-10-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
